services:
  postgis:
    image: postgis/postgis
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: o2p
      POSTGRES_USER: o2p
    networks:
      - postgis
  libpostal:
    image: pasupulaphani/libpostal-zeromq # 4242
#    image: pelias/libpostal-service # http 4400
    networks:
      - libpostal

  backend:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      postgis:
        condition: service_healthy
      libpostal:
        condition: service_healthy
    networks:
      - postgis
      - libpostal
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: postgis
      LIBPOSTAL_HOST: libpostal

networks:
  postgis:
    name: geocoding_postgis
  libpostal:
