services:
  postgis:
    image: postgis/postgis
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: o2p
      POSTGRES_USER: o2p
    networks:
      - postgis
    ports:
      - "5432:5432"
  libpostal:
    image: pasupulaphani/libpostal-zeromq # 4242
#    image: pelias/libpostal-service # http 4400
    ports:
      - "4242:4242"

networks:
  postgis: